# Generated by Django 4.1.5 on 2023-02-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='likes.like')),
            ],
            options={
                'verbose_name': 'comment like',
                'verbose_name_plural': 'Comment likes',
            },
            bases=('likes.like',),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='likes.like')),
            ],
            options={
                'verbose_name': 'post like',
                'verbose_name_plural': 'Post likes',
            },
            bases=('likes.like',),
        ),
    ]
