# Generated by Django 4.1.5 on 2023-02-13 11:09

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=12, unique=True, verbose_name='username')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='image')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+996123456789'.", regex='^\\+996\\d{9}$')], verbose_name='phone_number')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='bio')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='skill name')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='job_title')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Other', 'Other')], max_length=20, verbose_name='job_type')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='company_name')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='position')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('workplace_type', models.CharField(blank=True, choices=[('Office', 'Office'), ('Remote', 'Remote'), ('Other', 'Other')], max_length=20, null=True, verbose_name='workplace_type')),
                ('currently_working', models.BooleanField(default=False, verbose_name='currently_working')),
                ('start_date', models.DateField(auto_now=True, verbose_name='start_date')),
                ('end_date', models.DateField(auto_now=True, null=True, verbose_name='end_date')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_work_exp', to=settings.AUTH_USER_MODEL, verbose_name='user_work_exp')),
                ('skills', models.ManyToManyField(blank=True, null=True, related_name='skills', to='users.skills', verbose_name='skills')),
            ],
            options={
                'verbose_name': 'work experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='education name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='faculty')),
                ('start_date', models.DateField(auto_now=True, verbose_name='start date')),
                ('end_date', models.DateField(auto_now=True, null=True, verbose_name='end date')),
                ('graduated', models.BooleanField(default=False, verbose_name='graduated')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_educattion', to=settings.AUTH_USER_MODEL, verbose_name='user_educattion')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'Educations',
            },
        ),
    ]
