# Generated by Django 4.1.5 on 2023-02-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skills_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(related_name='skills', to='users.education', verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience',
            field=models.ManyToManyField(related_name='work_experience', to='users.workexperience', verbose_name='work_experience'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='users.skills', verbose_name='skills'),
        ),
    ]
