# Generated by Django 4.1.5 on 2023-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_education_alter_user_work_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(related_name='education', to='users.education', verbose_name='education'),
        ),
    ]
